console.log('Калькулятор скидки:');
let firstData = prompt('Write a value of product - ');
let secondData = prompt('Write a value of discount -');
let valueProduct = Number(firstData);
let valueDiscount = valueProduct * Number(secondData/100);
let totalPrice = valueProduct - valueDiscount;
console.log('value of product = ' + " " + valueProduct);
console.log('value of the discount = ' + " " + valueDiscount);
console.log('total price = ' + " " + totalPrice);
console.log('--------------slash-------------------');
console.log('Инфа по юзеру:');
let userName = prompt('Write your name - ');
let userAge = prompt('How old are you ?');
console.log('Your name is - ' + userName + ' you are - ' + userAge + ' years old.');
console.log('---------------slash------------------');
console.log('Умножить числа*:');
let sizeSideA = prompt('Enter first number for * - ');
let sizeSideB = prompt('Enter second number - ');
let squareRectangle = Number(sizeSideA) * Number(sizeSideB);
console.log('side A = ' + sizeSideA + ' side B = ' + sizeSideB + ' sqare the rectangle = ' + squareRectangle);
console.log('---------------slash------------------');
console.log('Поделить числа/:');
let sizeSideC = prompt('Write first number for / - ');
let sizeSideD = prompt('Write second number - ');
let squareRectangleCD = Number(sizeSideC) / Number(sizeSideD);
console.log('side C = ' + sizeSideC + ' side D = ' + sizeSideD + ' sqare the rectangle = ' + squareRectangleCD);
